### ISSUE TITLE
readme should be edited

### ISSUE THREAD

**Issue by apo-bozdag** [erayaydin/NVimArtisan#2]
### Discussed in https://github.com/erayaydin/NVimArtisan/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **apo-bozdag** July  1, 2022</sup>
I'm new to vim how can I use it :D</div>

**Comment by erayaydin** [comment]
For improve DX;

- ~I'll add `ArtisanUpdate` command.~
- ~Auto install packer in lua script.~
- ~More modular structure for the NVimArtisan setup.~
- ~Basic installation commands in the `readme.md` file.~
- ~Dockerize for easy testing.~

**Comment by erayaydin** [comment]
`Packer` was migrated to `lazy.nvim` in 0.4.0 version. `lazy.nvim` will be installed automatically. Modular structure will be implemented in future version. I gave up about dockerize NVimArtisan, maybe in future versions (help wanted). `ArtisanUpdate` command not be implemented until stable release (so much change regularly / cant afford to maintain stable update process).

Closing this issue. Please subscribe to 0.4.0 pull request or create discussion to ask usage questions.
